local rosewater = '#DC8A78'
local red = '#D20F39'
local green = '#40A02B'
local yellow = '#DF8E1D'
local blue = '#1E66F5'
local pink = '#EA76CB'
local teal = '#179299'
local text = '#4C4F69'
local subtext1 = '#5C5F77'
local subtext0 = '#6C6F85'
local surface2 = '#ACB0BE'
local surface1 = '#BCC0CC'
local base = '#EFF1F5'

return {
  color_background = base,
  color_foreground = text,
  color_bold = text,
  color_cursor = rosewater,
  color_cursor_foreground = base,
  color_highlight = rosewater,
  color_highlight_foreground = base,
  color_0  = subtext1, -- black (background)
  color_1  = red, -- red
  color_2  = green, -- green
  color_3  = yellow, -- brown
  color_4  = blue, -- blue
  color_5  = pink, -- purple
  color_6  = teal, -- cyan
  color_7  = surface2, -- light gray (foreground)
  color_8  = subtext0, -- gray
  color_9  = red, -- light red
  color_10 = green, -- light green
  color_11 = yellow, -- yellow
  color_12 = blue, -- light blue
  color_13 = pink, -- pink
  color_14 = teal, -- light cyan
  color_15 = surface1, -- white
}
